FROM mysql:5.7

MAINTAINER Sathiya Kirushnapillai <sathiya.kirushnapillai@heig-vd.ch> Mathieu Monteverde <mathieu.monteverde@heig-vd.ch> Michela Zucca <michela.zucca@heig-vd.ch>

ADD data/ /docker-entrypoint-initdb.d
