version: '2'
services:
  mysql:
    build: images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  phpmyadmin:
    build: images/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6060:80"
    links:
      - mysql:db

